### ISSUE TITLE
Generate Matterbridge Configuration

### ISSUE THREAD

**Issue by Apexal** [rcos/rcos-automation#3]
Matterbridge will be used to bridge channels between the existing Mattermost server and the new Discord server. We must have some host running Matterbridge at all times. To create channel bridges we simply need to add fields to the `matterbridge.toml` file. Instead of doing this manually, a script can generate the `toml` file for us:
- [x] generate valid toml file
- [x] automatically setup Mattermost and Discord credentials
- [x] accept a list of channel pairs to bridge
- [x] generate valid Matterbridge configuration file

**Comment by Apexal** [comment]
Here's some example output from the current version of the script:

```toml
[general]
IgnoreFailureOnStart = false

[discord] # Discord server connection settings
[discord.rcos]
Token = "DISCORD_BOT_TOKEN_HERE" # SECRET bot token found on https://discord.com/developers
Server = "DISCORD_SERVER_ID_HERE" # The ID of the Discord server. Can be found in URL when on Discord or if Developer Mode is turned on and right-clicking the server icon.
RemoteNickFormat = "*(from {PROTOCOL})* **{NICK}**: " # The prefix to apply to messages.

[mattermost] # Mattermost server connection settings
[mattermost.rcos]
Server = "chat.rcos.io:443" # URL of the Mattermost server with no http:// or https:// prepended
Team = "rcos" # The "team", found as the first part of URL when on Mattermost server
Login = "MATTERMOST_USERNAME_HERE" # Mattermost needs a user account to send/receive messages. This is the account username.
Password = "MATTERMOST_PASSWORD_HERE" # The password of the Mattermost account to use.
RemoteNickFormat = "*(from {PROTOCOL})* **{NICK}**: " # The prefix to apply to messages.

[[gateway]]
name = "gateway-0"
enable = true
[[gateway.inout]]
account = "discord.rcos"
channel = "announcements"

[[gateway.inout]]
account = "mattermost.rcos"
channel = "Announcements"


[[gateway]]
name = "gateway-1"
enable = true
[[gateway.inout]]
account = "discord.rcos"
channel = "fall-2020"

[[gateway.inout]]
account = "mattermost.rcos"
channel = "Town Square"


[[gateway]]
name = "gateway-2"
enable = true
[[gateway.inout]]
account = "discord.rcos"
channel = "helpdesk"

[[gateway.inout]]
account = "mattermost.rcos"
channel = "Helpdesk"


[[gateway]]
name = "gateway-3"
enable = true
[[gateway.inout]]
account = "discord.rcos"
channel = "small-group-1"

[[gateway.inout]]
account = "mattermost.rcos"
channel = "SmallGroup-Sage2112"
```
